RFC 5424 Logging Support
mmaul/cl-syslog pull request #8
Opened 2018-11-15 23:27 UTC by tarballs-are-good

This PR is adding [RFC 5424](https://www.rfc-editor.org/rfc/pdfrfc/rfc5424.txt.pdf) compliance to CL-SYSLOG. It does so by building atop existing functionality. In particular, it adds a new `rfc5424-logger` class, along with a `log-string` function and an `rfc-log` macro.

It is *incomplete* and ~*not ready to merge*~. There are still some TODO items:

- [x] Clean up the file a bit.
- [x] Figure out where and how streams should be used
- [x] Add README documentation
- [ ] Add tests

With that said, all features of RFC5424 are present, including structured data, and log processors seem to understand it OK.

2018-11-17 05:12 UTC, mmaul commented
Wow, love your code, comments very well written!!!
So thoughts:
I like your interface, especially the support for structured data

Since you switched from dot to slash as the package and "sub-package" separator it would be good to idea maintain the legacy package names for a while, but indicate they are depreciated. Not that it matters that much I don't think there is anything in quicklisp that relies on cl-syslog (I checked quickdocs, as a quick way to look). Frankly I like your slashes better.....

Another TODO might also be to implement TCP syslog if you want to go all in implement RFC 5425 Transport Layer Security (TLS) Transport Mapping for Syslog

If your goal is high performance computing you might consider a buffering mechanism to limit the number of network requests or syslog calls. Going a littler further decouple things a bit and make client interface coupled via message passing to the logging system and run that in a separate thread. Course this may be a little bit of overkill unless your goal is to support high throughput logging.

Perhaps set a default value for facility in rfc5424-logger, I'm thinking user

What might be nice is create a cl-syslog appender for log4cl.

Finally it seems like you have vision and perhaps a vested interest in this package so if you want to take over this project I could transfer the project over to you if you are interested.

2018-11-18 04:16 UTC, mmaul reviewed
Lke slashes better but should also keep systems with dots to keep from breaking code that may depend on cl-syslog, however should not be much.

2018-11-18 04:17 UTC, mmaul approved these changes
Lke slashes better but should also keep systems with dots to keep from breaking code that may depend on cl-syslog, however should not be much.

2018-11-19 17:39 UTC, tarballs-are-good commented
Note that the slashes are for ASDF conformance. I agree, it wouldn't hurt to make backward compat system names (in separate files) which can be deprecated and later deleted.

2018-12-13 22:39 UTC, tarballs-are-good commented
I am going to hold off adding tests. I don't want to figure out `NST` yet, and I'd probably prefer to replace it wholesale with a much simpler testing framework like Fiasco.

2018-12-13 22:45 UTC, tarballs-are-good commented
@mmaul I have implemented some of your requests:

1. I made the default facility `:USER`.
2. I created backwards compatible ASDF packages with the dotted-names. Note that the slashes are now ASDF-standard.
3. I decided not to touch the UDP package at all. It does cause compile-time style warnings.
4. I decoupled the log generation from the log transmission. Check out the `log-writer` slot, which can take any function at all. By default, it just calls into the normal `syslog`.
5. I wrote a bit of a longer README.

I think this is ready for merging, if you're OK with it not having extensive tests. I'm OK to be on the hook for fixing bugs, and slowly adding tests as time goes on.

2018-12-13 23:41 UTC, notmgsk requested changes

2018-12-13 23:41 UTC, notmgsk commented on README.md
> +> (ql:quickload :cl-syslog)`
trailing `

2018-12-13 23:41 UTC, notmgsk commented on README.md
> +instance, the priority `:warning` on facility `:user`. All of these
"on" or "or"? Might be correct as is

2018-12-13 23:41 UTC, notmgsk commented on README.md
> +followed by a usually 5 digit integer. For instance, `mycompany@0001`
That is not 5 digits. Maybe say "by a usually (but not necessarily) 5 digit integer"

2018-12-13 23:41 UTC, notmgsk commented on README.md
> +ASCII. It is also expect your Lisp's `char-code` matches ASCII. The
"It also expects that your..."

2018-12-13 23:44 UTC, notmgsk commented on rfc5424-reserved.lisp
> +  ;; TODO: actually parse an IP address
Do it

2018-12-14 00:56 UTC, tarballs-are-good commented on README.md
> +instance, the priority `:warning` on facility `:user`. All of these
on is correct

2018-12-14 01:20 UTC, notmgsk approved these changes

2018-12-18 18:52 UTC, notmgsk commented on README.md
> +ASCII. It is also expect that your Lisp's `char-code` matches
expected

2018-12-19 02:55 UTC, merged